ALTER TABLE tenants ADD COLUMN IF NOT EXISTS country_code CHAR(2) NOT NULL DEFAULT 'EG';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS map_center_lat DOUBLE PRECISION;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS map_center_lng DOUBLE PRECISION;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS map_zoom INTEGER NOT NULL DEFAULT 12;
